### ISSUE TITLE
Argument fields don't clear in UI when "Message to Send" changes

### ISSUE THREAD

**Issue by brettkolodny** [AcalaNetwork/evm-playground#3]
When executing a contract if a user changes from one `Message to Send` to another the previous arguments supplied are not cleared from the UI but are cleared within the page's state. This causes the call to fail with the cause not being apparent. To make the call succeed the user needs to clear out the field and renter the value.

The page should be updated to clear the argument fields whenever the `Message to Send` changes.

**Comment by ntduan** [comment]
Thank you, it has been fixed and redeployed.
